name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.SERVICE_ACCOUNT_CREDENTIALS }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install requirements
        run: python -m pip install -U -r requirements.txt

      - name: Install test requirements
        run: python -m pip install -U pytest pytest-cov

      - name: Run tests
        run: python -m pytest tests.py --cov=gspreaddb

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
