name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.SERVICE_ACCOUNT_CREDENTIALS }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Pip install
        run: python -m pip install -U -r requirements.txt

      - name: Run tests
        run: python tests.py
